[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
license_system = "5pXEX8z1aTSnm7jCKqvJCXezczKPVuPQif2BZh5u5Axq"

[programs.devnet]
license_system = "5pXEX8z1aTSnm7jCKqvJCXezczKPVuPQif2BZh5u5Axq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
